# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Avonya' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Avonya
   pod 'SDWebImage'

  target 'AvonyaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AvonyaUITests' do
    # Pods for testing
  end

end
